language: cpp
dist: trusty
sudo: required
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake
    - zlib1g-dev
before_script:
- "./build_deps.sh"
script:
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
- gcc -v && g++ -v && cmake --version
- ./set_version.sh
- cmake .
- make
- ./test/test.sh
after_success:
- ls -al
- openssl dgst -sha256 tagmp3
- gzip -9 tagmp3
- ls -l tagmp3.gz
- openssl dgst -sha256 tagmp3.gz
deploy:
  provider: releases
  api_key:
    secure: JNk2TJjPlLg5NUERhXjmkvfvjcxwvlPbwI/+3ButymQZWydKuP3GQZ1sz+7zYkwZ7cZe/ihOseL0hmVf7bxOjhorB35SofhDXAzDAMkr4bv/VTiSSjYGNq7J2Yz7xoBIKHP2HRmSPhqVuvvCOjHvIRwPvH4VpnSEPltvECTS3OGhu61cfKMKjPqYZltty5ih4tQSGF65sFt0MDCopLcKuZahtmQmMN6DddDgXOV90SvNLOngKtyQu9lUEe9AHNL3004EmARScjVMgXgKRa7PNiK3H/Lu5Y09Nuq6sP177Vs+Ab+2RD418j55KshW5Cfhp9zvd7ivQps/7RArGoBYyS1u2JOyzgOPGlXj2s3aAn1qh98jABXkxwNUdKvratWazXxvo4uaaMFmrqfz66oprR39mgYbn9KUM9JowCzY+VCLQVYVMmhEgspG6GkQRKQy3UhdcVNLHhgVCcnu2Agb/LJ8E/o07eBYoA24GIQ5xA6XjKvwpSBIA2XzQHFoH+40golrdlt7j5zLI93Gi6APZxlf5VFbBK0KYh9qhYEw9uPngLvy/XDUPSfMqee5pmnRYZokC64yLd6EMEDID6GGOYbAf4P7QLSQuLF+GybdNDWIhilQ+DHYArhsTSaoQFFwP9GjPRTruInyKgw6SxKa3C9PlQcM8MKNW82VdRCOgdo=
  file: 'tagmp3.gz'
  skip_cleanup: true
  on:
    repo: ooola/tagmp3
    tags: true
    # "Skipping a deployment with the releases provider because this is not a tagged commit"
    # will be displayed if no tags and tags is set to true
